### ISSUE TITLE
Support for Pivoted datasets in TreeMap

### ISSUE THREAD

**Issue by jpotter** [enveritas/looker-data-viz#4]
## Background

In some data setups, we want to generate tree maps where the two data columns that control parameters for (size, value) are generated from a pivot.

## Issue

Currently, when this happens, the TreeMap viz fails to render. If I had to guess, the data frame is including a header row for the pivot column names; removing that row would likely solve it.

<img width="868" alt="Screen Shot 2021-09-17 at 9 21 13 AM" src="https://user-images.githubusercontent.com/532530/133789410-58e6886e-acb3-453a-9caa-16e68973c56a.png">

**Comment by gjacobrobertson** [comment]
Shipped a pass at this in 5bf7359da0b80a41776982d28063601d8ae2afa4. See if that is sufficient?

**Comment by jpotter** [comment]
This is implemented!
