### ISSUE TITLE
When display the numeric value in TreeMap, number needs better formatting

### ISSUE THREAD

**Issue by jpotter** [enveritas/looker-data-viz#5]
## Background

There are a number of cases (groan) where number formatting could be better. This ends up mattering because without these fixed, screenshots of the data viz results can't be directly used, leading to more work for data viz consumers.

Example 1: Floats don't get rendered well:
<img width="236" alt="Screen Shot 2021-09-17 at 9 24 07 AM" src="https://user-images.githubusercontent.com/532530/133789765-26659701-592a-4586-b5e0-be7df567c269.png">
<img width="373" alt="Screen Shot 2021-09-17 at 9 52 36 AM" src="https://user-images.githubusercontent.com/532530/133794170-c90ad967-7229-4b40-ab30-8f9ffabdc4ff.png">

Example 2: Very large numbers are illegible:
<img width="368" alt="Screen Shot 2021-09-17 at 9 50 03 AM" src="https://user-images.githubusercontent.com/532530/133793699-293afe65-832e-46d7-909f-c70f465f373c.png">

## Proposed Solution

Formatting the numbers with conventional approaches (e.g. editing the dimension defintion) don't work with key-value based data. One possible solution: provide a number format field in the "gear" icon. Another possible solution: simply pick a convention and go with it -- i.e. for floats, display to 2 decimal digits; for numbers >1000, use the US-style convention of comma-delimited. So: `14,688,888.88` ... I'd personally be just fine with the quick-fix-format here as a first-pass, and waiting to see if there are ever any requests for better number formatting.

As a related: visually, I find having the numeric value at the same font size / color as the label to make it harder to read. I think a lot could be gained by making the numeric text value have 66% opacity and removing the `()` characters, and something like two spaces optically between label and value.

**Comment by gjacobrobertson** [comment]
it currently tries to format according to the `value_format` of the measure being displayed https://docs.looker.com/reference/field-params/value_format

We could add some default formatting in there but I imagine in a lot of cases with the geo dataset stuff you don't know what the best format is until you've picked a particular scoring variable, which isn't a measure. Should be pretty easy to add an override in the config.

**Comment by gjacobrobertson** [comment]
5bf7359da0b80a41776982d28063601d8ae2afa4 adds a config field for value format. It is kinda excel-ish so you could do something like `0,000` to use comma separators and no decimal places, `$0,000.00` to prefix with dollar signs, group with commas, and 2 decimal places, or use the special suffix `s` for SI suffixes so like `0.00s` would format `1234567` to `1.23M`

**Comment by jpotter** [comment]
Thanks! @gjacobrobertson! Although it looks like this broke it -- see https://enveritas.looker.com/explore/jebena/geo_map_dataset?qid=H1oHHfPMjzDmglrkxSXVPK&toggle=fil,vis for an example -- I simply see a blank viz page for the link that I know worked before. I tried entering "0.0" into the new config field in case the empty state for the numeric format was the cause of the blank screen, but no dice. This occurs in both Safari and Chrome.
